apiVersion: v1
kind: Service
metadata:
  labels:
    app: vbulletin
  name: vbulletin
spec:
  ports:
  - name: 80-30007
    nodePort: 30009
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: vbulletin
  type: NodePort
