apiVersion: v1
kind: Service
metadata:
  labels:
    app: jira
  name: jira
spec:
  ports:
  - name: 8080-30080
    nodePort: 30010
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: jira
  type: NodePort
